name: Build and Push Docker Image

on:
  push:
    paths:
      - Dockerfile
      - root/**
  workflow_dispatch:


env:
  IS_DEFAULT_BRANCH: ${{ github.ref_name == github.event.repository.default_branch }}
  TEST_TAG: prowler1000/mini-localai:test
  LOCALAI_VER: v2.13.0
  GRPC_VER: v1.58.0


jobs:
  build_grpc:
    name: Build gRPC
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build gRPC
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            GRPC_VERSION=${{ env.GRPC_VER }}
          cache-to: type=registry,ref=${{ vars.GRPC_TAG }}:${{ env.GRPC_VER }}
          cache-from: type=registry,ref=${{ vars.GRPC_TAG }}:${{ env.GRPC_VER }}
          target: grpc

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build_grpc
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build LocalAI
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          cache-to: type=registry,ref=${{ vars.BUILD_CACHE_TAG }}:${{ env.LOCALAI_VER }}
          cache-from: |
            type=registry,ref=${{ vars.GRPC_TAG }}:${{ env.GRPC_VER }}
            type=registry,ref=${{ vars.BUILD_CACHE_TAG }}:${{ env.LOCALAI_VER }}
          target: localai-builder

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            prowler1000/${{ vars.IMAGE_PATH }}
          tags: |
            type=raw,value=latest
            type=raw,value=stable,enable=${{ env.IS_DEFAULT_BRANCH == 'true' }}
            type=ref,event=branch,enable=${{ env.IS_DEFAULT_BRANCH == 'false' }}

      - name: Build final
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=registry,ref=${{ vars.FINAL_CACHE_TAG }}:${{ env.LOCALAI_VER }}
          cache-from: |
            type=registry,ref=${{ vars.GRPC_TAG }}:${{ env.GRPC_VER }}
            type=registry,ref=${{ vars.BUILD_CACHE_TAG }}:${{ env.LOCALAI_VER }}
            type=registry,ref=${{ vars.FINAL_CACHE_TAG }}:${{ env.LOCALAI_VER }}
