name: Test Docker Image

on:
    workflow_call:
        inputs:
            cache_suffix:
                required: false
                type: string
            test_tag:
                required: true
                type: string

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
          - name: Parse suffix
            id: parse
            run: |
                if [[ -n "${{ inputs.scope_suffix }}" && "${{ inputs.scope_suffix }}" != _* ]]; then
                    echo "scope_suffix=_${{ inputs.scope_suffix }}" >> "$GITHUB_OUTPUT"
                else
                    echo "scope_suffix=${{ inputs.scope_suffix }}" >> "$GITHUB_OUTPUT"
                fi
          - name: Check out the repo
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build final
            uses: docker/build-push-action@v5
            with:
                context: .
                push: false
                load: true
                tags: ${{ inputs.test_tag }}
                cache-from: |
                    type=gha, scope=grpc
                    type=gha, scope=grpc${{ steps.parse.outputs.scope_suffix}}
                    type=gha, scope=localai
                    type=gha, scope=localai${{ steps.parse.outputs.scope_suffix }}
                    type=gha, scope=final
                    type=gha, scope=final${{ steps.parse.outputs.scope_suffix }}

          - name: Test image
            run: |
                docker run --rm ${{ inputs.test_tag }}